name: 数据集访问申请（Dataset Access Application）
description: 申请获取 The REFN Dataset（请先下载并签署许可证 PDF）
title: "数据集申请：${{ inputs.name }} - ${{ inputs.organization }}"
labels: ["application"]
# assignees: ["你的GitHub用户名"]   # 可选：自动指派给审核人

body:
  - type: markdown
    attributes:
      value: |
        **请先下载并签署许可证：**
        https://scut-acig.github.io/dataset-site/assets/REFN_Dataset_License.pdf

        提交本表单后，请在本 Issue 的评论区**拖拽上传**已签署的 PDF（或粘贴网盘链接）。

  - type: input
    id: name
    attributes:
      label: 姓名 / Name
      placeholder: 例如：张三
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: 电子邮箱 / Email
      description: 我们会通过该邮箱联系你（请确保可接收外部邮件）
      placeholder: your@email.com
    validations:
      required: true

  - type: dropdown
    id: country
    attributes:
      label: 国家 / Country
      options:
        - 中国
        - 新加坡
        - 美国
        - 英国
        - 德国
        - 日本
        - 韩国
        - 其他
    validations:
      required: true

  - type: input
    id: organization
    attributes:
      label: 机构 / Organization
      placeholder: 学校/公司全称
    validations:
      required: true

  - type: input
    id: department
    attributes:
      label: 部门 / Department（可选）
      placeholder: 学院/系/研究所

  - type: input
    id: lab_url
    attributes:
      label: 实验室主页（可选）/ Lab Homepage (optional)
      placeholder: https://...

  - type: input
    id: position
    attributes:
      label: 职位 / Position
      placeholder: 学生 / 研究员 / 工程师 等
    validations:
      required: true

  - type: input
    id: advisor_name
    attributes:
      label: 主管/导师姓名（可选）/ Advisor (optional)

  - type: input
    id: advisor_email
    attributes:
      label: 主管/导师邮箱（可选）/ Advisor Email (optional)

  - type: textarea
    id: usage
    attributes:
      label: 数据集用途说明 / Intended Use
      description: 简述项目名称、研究方向、预计成果（最多 300 字）
      placeholder: 我将在课题《……》中用于……，成果预计……
    validations:
      required: true

  - type: checkboxes
    id: agreement
    attributes:
      label: 使用承诺 / Agreement
      options:
        - label: 我承诺仅将该数据集用于学术研究，遵守许可证条款，不用于任何商业目的。
          required: true

  - type: markdown
    attributes:
      value: |
        **重要：**提交后，请在本 Issue 的评论区**拖拽上传**已签署的许可证 PDF（或粘贴云盘链接）。
        若无法上传，请邮件联系我们：qchm@scut.edu.cn
