name: Dataset Access Application
description: Apply for access to The REFN Dataset (please download and sign the license PDF first)
title: "Dataset Application: ${{inputs.name}} - ${{inputs.organization}}"
labels: ["application"]
# assignees: ["your-github-username"]   # optional: auto-assign to reviewer

body:
  - type: markdown
    attributes:
      value: |
        **Please download and sign the license first:**
        https://scut-acig.github.io/dataset-site/assets/REFN_Dataset_License_Agreement.pdf

        After submitting this form, please **upload the signed PDF** in the comments of this Issue (or provide a cloud link).

  - type: input
    id: name
    attributes:
      label: Full Name
      placeholder: e.g., John Smith
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Email Address
      description: We will contact you via this email (please make sure it is valid).
      placeholder: your@email.com
    validations:
      required: true

  - type: dropdown
    id: country
    attributes:
      label: Country
      options:
        - China
        - Singapore
        - United States
        - United Kingdom
        - Germany
        - Japan
        - Korea
        - Other
    validations:
      required: true

  - type: input
    id: organization
    attributes:
      label: Organization
      placeholder: University / Company full name
    validations:
      required: true

  - type: input
    id: department
    attributes:
      label: Department (optional)
      placeholder: School / Department / Institute

  - type: input
    id: lab_url
    attributes:
      label: Lab Homepage (optional)
      placeholder: https://...

  - type: input
    id: position
    attributes:
      label: Position
      placeholder: Student / Researcher / Engineer etc.
    validations:
      required: true

  - type: input
    id: advisor_name
    attributes:
      label: Advisor Name (optional)

  - type: input
    id: advisor_email
    attributes:
      label: Advisor Email (optional)

  - type: textarea
    id: usage
    attributes:
      label: Intended Use
      description: Briefly describe your project, research direction, and expected outcome (max 300 words).
      placeholder: I will use the dataset in the project "..." for ..., expected outcome is ...
    validations:
      required: true

  - type: checkboxes
    id: agreement
    attributes:
      label: Usage Agreement
      options:
        - label: I confirm that this dataset will be used for academic research only, in compliance with the license agreement, and not for any commercial purpose.
          required: true

  - type: markdown
    attributes:
      value: |
        **Important:** After submitting, please upload the signed license PDF in the comments of this Issue (or paste a cloud link).
        If you cannot upload, please contact us via email: qchm@scut.edu.cn
   - type: markdown
     attributes:
    value: |
      <!-- NAME: ${{ inputs.name }} -->
      <!-- ORG:  ${{ inputs.organization }} -->
