name: Retitle new dataset applications
on:
  issues:
    types: [opened]

jobs:
  retitle:
    if: contains(github.event.issue.labels.*.name, 'application')
    runs-on: ubuntu-latest
    steps:
      - name: Extract fields from issue body
        id: parse
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || "";
            // Forms usually render like:
            // **Full Name**
            // John Smith
            //
            // **Organization**
            // Tsinghua University
            function valueAfter(label){
              const re = new RegExp(`\\*\\*${label}\\*\\*\\s*\\n+\\s*([\\s\\S]*?)(\\n\\n|$)`, 'i');
              const m = body.match(re);
              return m ? m[1].trim() : "";
            }
            const name = valueAfter("Full Name");
            const org  = valueAfter("Organization");
            core.setOutput("name", name);
            core.setOutput("org", org);

      - name: Update issue title
        uses: actions/github-script@v7
        with:
          script: |
            const name = `${{ steps.parse.outputs.name }}` || "Unknown";
            const org  = `${{ steps.parse.outputs.org }}`  || "Unknown";
            const newTitle = `Dataset Application: ${name} - ${org}`;
            await github.rest.issues.update({
              ...context.repo,
              issue_number: context.issue.number,
              title: newTitle
            });
